# Generated by Django 4.1.5 on 2023-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Middel_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Adress', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Delhi', 'Delhi')], max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('Aadhar_No', models.PositiveIntegerField()),
                ('Pan_no', models.CharField(max_length=10)),
                ('project_Location', models.CharField(choices=[('Odisha', 'Odisha'), ('Hathras', 'Hathras'), ('Aligarh', 'Aligarh'), ('Bptp', 'Bptp'), ('Imt_Faridabad', 'Imt_Faridabad'), ('Mcf', 'Mcf'), ('Dwarka', 'Dwarka'), ('Ashok Vihar', 'Ashok Vihar'), ('Jhansi', 'Jhansi'), ('Imlota', 'Imlota'), ('Head Office', 'Head Office'), ('Rajasthan', 'Rajasthan'), ('Behror', 'Behror'), ('Bhopal', 'Bhopal'), ('Sehore', 'Sehore'), ('Jhajjar', 'Jhajjar'), ('Barwala', 'Barwala'), ('Puran Pur', 'Puran Pur'), ('Nagar', 'Nagar'), ('Jaisalmer', 'Jaisalmer'), ('Kostnallah', 'Kostnallah'), ('Rpd-1', 'Rpd-1'), ('Guhana-Sonepat-II', 'Guhana-Sonepat-II'), ('Jalaun', 'Jalaun'), ('Jind-Guhana-I', 'Jind-Guhana-I')], max_length=100)),
                ('Driving_License', models.CharField(max_length=25)),
                ('DL_issue_Date', models.DateField()),
                ('upload_DL', models.ImageField(blank=True, upload_to='Dlimg')),
                ('my_file', models.FileField(blank=True, upload_to='Doc')),
            ],
        ),
    ]
