# Generated by Django 4.1.5 on 2023-01-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='First_Name',
            new_name='Candidate_Name',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='Middel_Name',
        ),
    ]
